---
- name: Generate Switch Baseline Configurations
  hosts: core_switches
  gather_facts: false

  tasks:
    - name: Render Jinja2 template to local text files
      template:
        src: switch_config.j2
        dest: "./{{ inventory_hostname }}_vlan.txt"
