---
- name: Loopback config
  hosts: all
  gather_facts: false

  tasks:
    - name: Push loopback IPs
      ansible.netcommon.cli_config:
        config: |
          interface lo
          ip address {{ loopback_ip }}

    - name: save the config
      ansible.netcommon.cli_command:
        command: write memory
