---
- name: Push OSPF configuration
  ansible.netcommon.cli_config:
    config: "{{ lookup('template', 'router_config.j2') }}"
  notify: Save the configuration

- name: Push the BGP neighbor template
  ansible.netcommon.cli_config:
    config: "{{ lookup('template', 'bgp_neighbors.j2') }}"
  notify: Save the configuration
